import { z } from 'zod';

export const commitSizeSchema = z.enum(['XS', 'S', 'M', 'L', 'XL']);

export const fileStatusSchema = z.object({
  status: z.string(),
  file: z.string(),
  oldFile: z.string().optional(),
  similarityScore: z.number().int().optional(),
  insertions: z.number().int().optional(),
  deletions: z.number().int().optional(),
  isBinary: z.boolean().optional(),
  language: z.string().optional(),
});

export const entrySchema = z.object({
  commit: z.string(),
  parents: z.array(z.string()).optional(),
  refs: z.array(z.string()).optional(),
  tags: z.array(z.string()).optional(),
  author: z.string(),
  email: z.string().optional(),
  committer: z.string().optional(),
  committerEmail: z.string().optional(),
  committerDate: z.string().optional(),
  date: z.string(),
  type: z.string().optional(),
  scope: z.string().optional(),
  isBreaking: z.boolean().optional(),
  breakingChangeDescription: z.string().optional(),
  isRevert: z.boolean().optional(),
  revertedCommit: z.string().optional(),
  isRebased: z.boolean().optional(),
  subject: z.string(),
  cleanSubject: z.string().optional(),
  body: z.string().optional(),
  isBodyTruncated: z.boolean().optional(),
  size: commitSizeSchema.optional(),
  files: z.array(fileStatusSchema).optional(),
  fileCount: z.number().int().optional(),
  isFilesTruncated: z.boolean().optional(),
  totalInsertions: z.number().int().optional(),
  totalDeletions: z.number().int().optional(),
  metadata: z.object({
    category: z.array(z.string()).optional(),
    entry: z.array(z.string()).optional(),
    significance: z.string().optional(),
    impact: z.union([z.number(), z.string()]).optional(),
    trust: z.union([z.number(), z.string()]).optional(),
    confidence: z.union([z.number(), z.string()]).optional(),
    validation: z.string().optional(),
    customTrailers: z.record(z.string(), z.array(z.string())).optional(),
  }).optional(),
  trailersObj: z.record(z.string(), z.string()).optional(),
  patch: z.string().optional(),
  isPatchTruncated: z.boolean().optional(),
  references: z.array(z.string()).optional(),
  coAuthors: z.array(z.string()).optional(),
  reviewers: z.array(z.string()).optional(),
  associatedIssues: z.array(z.object({
    issue: z.string(),
    action: z.string().nullable()
  })).optional(),
  slackId: z.string().optional(),
  validationErrors: z.array(z.unknown()).optional(),
  isCorrupted: z.boolean().optional(),
});

export type CommitEntry = z.infer<typeof entrySchema>;
export type FileStatus = z.infer<typeof fileStatusSchema>;

export const cliArgsSchema = z.object({
  limit: z.coerce.number().int().min(0).optional(),
  path: z.string().optional(),
  author: z.string().optional(),
  search: z.string().optional(),
  grep: z.string().optional(),
  range: z.string().optional(),
  since: z.string().optional(),
  until: z.string().optional(),
  'first-parent': z.boolean().optional(),
  help: z.boolean().optional(),
  'include-merges': z.boolean().optional(),
  'include-patch': z.boolean().optional(),
  'diff-context': z.coerce.number().int().min(0).optional(),
  'max-body-length': z.coerce.number().int().min(0).optional(),
  'max-patch-length': z.coerce.number().int().min(0).optional(),
  category: z.string().optional(),
  type: z.string().optional(),
  breaking: z.boolean().optional(),
  impact: z.string().optional(),
  confidence: z.string().optional(),
  jsonl: z.boolean().optional(),
  'changelog-only': z.boolean().optional(),
  format: z.string().optional(),
  summary: z.boolean().optional(),
  stats: z.boolean().optional(),
  all: z.boolean().optional(),
  'patch-search': z.string().optional(),
  'diff-filter': z.string().optional(),
  reverse: z.boolean().optional(),
  'no-body': z.boolean().optional(),
  'issue-tracker': z.string().optional(),
  'issue-pattern': z.string().optional(),
  cache: z.boolean().optional(),
  mailmap: z.string().optional(),
  'slack-map': z.string().optional(),
  'package-version': z.boolean().optional(),
  'stream-to-file': z.string().optional(),
  uncommitted: z.boolean().optional(),
});

export type CliArgs = z.infer<typeof cliArgsSchema>;
