import { test, describe } from 'bun:test';
import { checkPrompt } from '../prompt-detector.js';

describe('prompt-detector.ts heuristics', () => {
  test('inquirer.js prompts', () => {
    const prompts = [
      "? Would you like to continue? (Y/n) ",
      "? Select an option: ",
      "? Choose your package manager: › - Use arrow-keys. Return to submit.",
      " ? What is your name? ",
      " ? What is your name? (default)"
    ];
    for (const prompt of prompts) {
      if (!checkPrompt(prompt)) {
        throw new Error(`Failed to detect inquirer prompt: ${prompt}`);
      }
    }
  });

  test('y/n prompts', () => {
    const prompts = [
      "Do you want to continue? [y/N] ",
      "Overwrite? (y/n) ",
      "Are you sure? (yes/no)? ",
      "Are you sure? [y/N] "
    ];
    for (const prompt of prompts) {
      if (!checkPrompt(prompt)) {
        throw new Error(`Failed to detect y/n prompt: ${prompt}`);
      }
    }
  });

  test('git rebase -i blocking prompt', () => {
    const prompts = [
      "hint: waiting for your editor to close the file"
    ];
    for (const prompt of prompts) {
      if (!checkPrompt(prompt)) {
        throw new Error(`Failed to detect git rebase -i prompt: ${prompt}`);
      }
    }
  });

  test('forced TTY prompts', () => {
    // This is checking if standard output generated by forced TTY like bash -i is caught
    const prompts = [
      "bash-5.1$ ",
      "root@localhost# ",
      "user@ubuntu:~$ ",
      "sh-5.1$ ",
      "bash-5.1# ",
      "bash$ ",
      "sh$ ",
      "~ $ ",
      "/ # ",
      "PS C:\\> "
    ];
    for (const prompt of prompts) {
      if (!checkPrompt(prompt)) {
        throw new Error(`Failed to detect forced TTY prompt: ${prompt}`);
      }
    }
  });

  test('editor blocking prompts', () => {
    const prompts = [
      "Waiting for Emacs...",
      "Waiting for nano...",
      "Waiting for vim...",
      "Waiting for vi...",
      "hint: Waiting for your editor to close the file...",
      "Waiting for Notepad..."
    ];
    for (const prompt of prompts) {
      if (!checkPrompt(prompt)) {
        throw new Error(`Failed to detect editor prompt: ${prompt}`);
      }
    }
  });

  test('gh CLI interactive prompts', () => {
    const prompts = [
      "? Title ",
      "? Body ",
      "? Title: ",
      "? Body: ",
      "Title: ",
      "Body: ",
      "? Title",
      "? Body",
      "? What's next?",
      "? Choose a template",
      "? Choose a template: "
    ];
    for (const prompt of prompts) {
      if (!checkPrompt(prompt)) {
        throw new Error(`Failed to detect gh CLI interactive prompt: '${prompt}'`);
      }
    }
  });

  test('sudo and password prompts', () => {
    const prompts = [
      "[sudo] password for chris:",
      "Password:",
      "Password for user:",
      "Enter passphrase for key:"
    ];
    for (const prompt of prompts) {
      if (!checkPrompt(prompt)) {
        throw new Error(`Failed to detect sudo/password prompt: '${prompt}'`);
      }
    }
  });
});
